apiVersion: v1
kind: Service
metadata:
  name: project-front-end
spec:
  selector:
    app: project-front-end
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-front-end
  labels: 
    app: project-front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-front-end
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: project-front-end
    spec:
      containers:
      - name: project-front-end
        image: davidpapworth2/project_front_end:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: database-uri
              key: databaseURI
