---
# tasks file for nginx

# nginx install
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  register: nignx_time

- name: check install
  debug:
    msg: "{{ nignx_time }}"

- name: Start nginx
  service:
    name: nginx
    state: started

# template file into machine 
- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: /templates/nginx.conf
    dest: /etc/nginx.conf
    owner: bin
    group: wheel
    mode: '0644'
  

# reload nginx
- name: Restart nginx if needed
  service:
    name: nginx
    state: restarted
  when: nginx_config.changed == true