---
# tasks file for nginx

# nginx install
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  register: nignx_time

- name: check install
  debug:
    msg: "{{ nignx_time }}"

- name: Start nginx
  service:
    name: nginx
    state: started

# template file into machine 
- name: Copy nginx file over
  copy:
    src: nginx.conf
    dest: /etc/templates/nginx.conf
  register: nginx_config
  
- name: check copy
  debug:
    msg: "{{ nginx_config }}"

# reload nginx
- name: Restart nginx if needed
  service:
    name: nginx
    state: restarted
  when: nginx_config.changed == true