---
# tasks file for nginx

# nginx install
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  register: nignx_time

- name: Start nginx
  service:
    name: nginx
    state: started

# template file into machine 
- name: Template a file to /etc/file.conf
  template:
    src: nginx.conf
    dest: /etc/nginx.conf


# reload nginx
- name: Restart nginx if needed
  service:
    name: nginx
    state: restarted
  when: nginx_config.changed == true