---
- name: "Install dependencies"
  apt:
    pkg:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg 
    - lsb-release
    - python3
    - python3-pip

- name: "Get Docker APT key"
  ansible.builtin.apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: "Add docker apt repo"
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: "Install docker"
  apt:
    pkg:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: "Add the user" 
  ansible.builtin.user:
    name: pappy
    groups: docker
    append: yes

- name: "Install Docker with pip"
  pip:
    name: docker
    executable: pip3

